Repository hometerview/Android, pull requests merged in 2022-07, with the labels that each got.

#3 1/social login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/ui/login/LoginActivity.kt
  app/src/main/res/drawable/kakao_login_button.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/dimen.xml
Labels: question

#4 [로그인] Splash 화면 구현
  app/build.gradle
  app/src/main/java/com/ftw/hometerview/config/HometerviewApplication.kt
  app/src/main/java/com/ftw/hometerview/di/datasource/TokenDataSourceModule.kt
  app/src/main/java/com/ftw/hometerview/di/dispatcher/DispatcherModule.kt
  app/src/main/java/com/ftw/hometerview/di/repository/LoginRepositoryModule.kt
  app/src/main/java/com/ftw/hometerview/di/repository/TokenRepositoryModule.kt
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/LoginUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/TokenUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/di/util/ProviderModule.kt
  app/src/main/java/com/ftw/hometerview/dispatcher/AppDispatcher.kt
  app/src/main/java/com/ftw/hometerview/dispatcher/Dispatcher.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle
  data/src/main/java/com/ftw/data/datasource/TokenDataSource.kt
  data/src/main/java/com/ftw/data/local/datasource/TokenLocalDataSource.kt
  data/src/main/java/com/ftw/data/repository/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ftw/data/repository/token/TokenRepositoryImpl.kt
  domain/src/main/java/com/ftw/domain/repository/login/LoginRepository.kt
  domain/src/main/java/com/ftw/domain/repository/token/TokenRepository.kt
  domain/src/main/java/com/ftw/domain/usecase/login/LoginUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/login/LoginUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/token/GetStoredTokenUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/token/GetStoredTokenUseCaseImpl.kt
  versions.gradle
Labels: feature logic

#8 1/login
  .gitignore
  app/build.gradle
  app/proguard/proguard-kakao.pro
  app/proguard/proguard-retrofit2.pro
  app/proguard/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/config/DataStore.kt
  app/src/main/java/com/ftw/hometerview/config/HometerviewApplication.kt
  app/src/main/java/com/ftw/hometerview/di/api/APIModule.kt
  app/src/main/java/com/ftw/hometerview/di/api/NetworkModule.kt
  app/src/main/java/com/ftw/hometerview/di/datasource/LoginDataSourceModule.kt
  app/src/main/java/com/ftw/hometerview/di/datasource/TokenDataSourceModule.kt
  app/src/main/java/com/ftw/hometerview/di/dispatcher/DispatcherModule.kt
  app/src/main/java/com/ftw/hometerview/di/repository/LoginRepositoryModule.kt
  app/src/main/java/com/ftw/hometerview/di/repository/TokenRepositoryModule.kt
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/LoginUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/TokenUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/di/util/ProviderModule.kt
  app/src/main/java/com/ftw/hometerview/dispatcher/AppDispatcher.kt
  app/src/main/java/com/ftw/hometerview/dispatcher/Dispatcher.kt
  app/src/main/java/com/ftw/hometerview/ui/login/LoginActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable/kakao_login_button.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  build.gradle
  data/build.gradle
  data/proguard/consumer-rules.pro
  data/proguard/proguard-rules.pro
  data/src/main/java/com/ftw/data/datasource/LoginDataSource.kt
  data/src/main/java/com/ftw/data/datasource/TokenDataSource.kt
  data/src/main/java/com/ftw/data/local/datasource/TokenLocalDataSource.kt
  data/src/main/java/com/ftw/data/local/datastore/DataStoreKeys.kt
  data/src/main/java/com/ftw/data/local/datastore/DataStoreProvider.kt
  data/src/main/java/com/ftw/data/network/datasource/LoginRemoteDataSource.kt
  data/src/main/java/com/ftw/data/remote/api/LoginAPI.kt
  data/src/main/java/com/ftw/data/repository/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ftw/data/repository/token/TokenRepositoryImpl.kt
  domain/build.gradle
  domain/src/main/AndroidManifest.xml
  domain/src/main/java/com/ftw/domain/repository/login/LoginRepository.kt
  domain/src/main/java/com/ftw/domain/repository/token/TokenRepository.kt
  domain/src/main/java/com/ftw/domain/usecase/LoginUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/LoginUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/login/LoginUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/login/LoginUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/token/GetStoredTokenUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/token/GetStoredTokenUseCaseImpl.kt
  gradlew.bat
  local.properties
  settings.gradle
  versions.gradle
Labels: duplicate

#9 [버튼] Button 컴포넌트 추가
  app/build.gradle
  app/src/main/res/values/colors.xml
  design/.gitignore
  design/build.gradle
  design/consumer-rules.pro
  design/proguard-rules.pro
  design/src/androidTest/java/kr/co/remember/design/ExampleInstrumentedTest.kt
  design/src/main/AndroidManifest.xml
  design/src/main/java/kr/co/remember/design/Button.kt
  design/src/main/res/color/selector_button_color.xml
  design/src/main/res/color/selector_button_number_color.xml
  design/src/main/res/drawable/bg_button_disabled.xml
  design/src/main/res/drawable/bg_button_normal.xml
  design/src/main/res/drawable/bg_button_pressed.xml
  design/src/main/res/drawable/icon_like.xml
  design/src/main/res/drawable/selector_bg_button.xml
  design/src/main/res/font/pretendard_bold.otf
  design/src/main/res/font/pretendard_medium.otf
  design/src/main/res/font/pretendard_regular.otf
  design/src/main/res/font/pretendard_semibold.otf
  design/src/main/res/layout/view_button.xml
  design/src/main/res/values/attrs.xml
  design/src/main/res/values/colors.xml
  design/src/main/res/values/dimens.xml
  design/src/test/java/kr/co/remember/design/ExampleUnitTest.kt
  settings.gradle
Labels: feature logic
