Repository hometerview/Android, pull requests merged in 2022-08, with the labels that each got.

#11 [Main 화면] MainActivity 에 BottomNavigationView 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/di/api/NetworkModule.kt
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/bindingadapter/BottomNavigationViewAdapter.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/favorite/FavoriteFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/favorite/FavoriteViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/map/MapFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/map/MapViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashActivity.kt
  app/src/main/res/color/selector_main_bottom_navigation_color.xml
  app/src/main/res/drawable/icon_heart.xml
  app/src/main/res/drawable/icon_home.xml
  app/src/main/res/drawable/icon_map.xml
  app/src/main/res/drawable/icon_user.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_favorite.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/menu/menu_main_bottom_navigation.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  versions.gradle
Labels: feature ui

#10 6/onboarding
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/adapter/AnimationAdapter.kt
  app/src/main/java/com/ftw/hometerview/adapter/DiffCallback.kt
  app/src/main/java/com/ftw/hometerview/adapter/RecycleItem.kt
  app/src/main/java/com/ftw/hometerview/adapter/RecyclerAdapter.kt
  app/src/main/java/com/ftw/hometerview/bindingadapter/RecyclerDataBinding.kt
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/loading/LoadingActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/login/LoginActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompany/SearchCompanyActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanynonresult/SearchCompanyNonResultActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanynonresult/enrollcompanyname/EnrollCompanyNameFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanynonresult/searchcompanyaddress/SearchCompanyAddressFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanyresult/SearchCompanyResultActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanyresult/SearchCompanyResultViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/searchcompanyresult/recyclemodel/SearchResultRecycleModel.kt
  app/src/main/java/com/ftw/hometerview/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/button_enroll_company.xml
  app/src/main/res/drawable/ic_baseline_navigate_before_24.xml
  app/src/main/res/drawable/ic_baseline_navigate_next_24.xml
  app/src/main/res/drawable/ic_baseline_search_24.xml
  app/src/main/res/layout/activity_loading.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_search_company.xml
  app/src/main/res/layout/activity_search_company_non_result.xml
  app/src/main/res/layout/activity_search_company_result.xml
  app/src/main/res/layout/fragment_enroll_company_name.xml
  app/src/main/res/layout/fragment_search_company_address.xml
  app/src/main/res/layout/list_item_guide.xml
  app/src/main/res/layout/list_item_search_result.xml
  app/src/main/res/raw/loading.gif
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  design/src/main/java/kr/co/remember/design/Button.kt
  design/src/main/res/values/colors.xml
  domain/src/main/java/com/ftw/domain/entitiy/SearchResult.kt
  versions.gradle
Labels: feature ui

#12 [홈 화면 - 01] 홈 화면 일부 구현
  app/build.gradle
  app/src/main/java/com/ftw/hometerview/di/ui/MainFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/ReviewUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/UserUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/ui/bindingadapter/BottomNavigationViewBindingAdapter.kt
  app/src/main/java/com/ftw/hometerview/ui/main/MainActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewPagerAdapter.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/review/LocationListViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/review/LocationReviewListFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_location_list.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  domain/src/main/java/com/ftw/domain/entity/BuildingType.kt
  domain/src/main/java/com/ftw/domain/entity/Company.kt
  domain/src/main/java/com/ftw/domain/entity/LocationReview.kt
  domain/src/main/java/com/ftw/domain/entity/Review.kt
  domain/src/main/java/com/ftw/domain/entity/User.kt
  domain/src/main/java/com/ftw/domain/usecase/review/GetLocaionReviewsUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/review/GetLocationReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/user/GetCachedUserUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/user/GetCachedUserUseCaseImpl.kt
Labels: feature ui

#13 [홈 화면 - 02] 디자인 모듈 패키지명 변경
  design/src/androidTest/java/com/ftw/hometerview/design/ExampleInstrumentedTest.kt
  design/src/main/AndroidManifest.xml
  design/src/main/java/com/ftw/hometerview/design/Button.kt
  design/src/test/java/com/ftw/hometerview/design/ExampleUnitTest.kt
Labels: refactoring

#16 [템플릿] PR 및 Issue 템플릿 정의
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 #7 Button/메인 버튼 :
  app/build.gradle
  app/src/main/java/com/ftw/hometerview/ui/main/map/MapFragment.kt
  app/src/main/res/anim/appear_translate.xml
  app/src/main/res/anim/disappear_translate.xml
  app/src/main/res/layout/fragment_enroll_company_name.xml
  design/src/main/java/kr/co/remember/design/MainButton.kt
  design/src/main/res/drawable/button_main_button.xml
  design/src/main/res/layout/view_main_button.xml
  design/src/main/res/values/attrs.xml
  design/src/main/res/values/dimens.xml
Labels: feature ui

#18 6/collapsed toolbar
  app/src/main/java/com/ftw/hometerview/ui/buildingreview/BuildingReviewActivity.kt
  app/src/main/res/drawable/ic_baseline_chevron_left_24.xml
  app/src/main/res/layout/activity_building_review.xml
Labels: question, feature ui

#21 [홈] 홈 화면 디자인 적용
  app/src/main/java/com/ftw/hometerview/adapter/SpacingItemDecoration.kt
  app/src/main/java/com/ftw/hometerview/bindingadapter/RecyclerDataBinding.kt
  app/src/main/java/com/ftw/hometerview/ui/buildingreview/BuildingReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/main/HomeTabItemView.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/review/LocationReviewListFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/review/LocationReviewListViewModel.kt
  app/src/main/res/color/selector_building_review_collapsed_tab_text_color.xml
  app/src/main/res/color/selector_building_review_expanded_tab_text_color.xml
  app/src/main/res/drawable-xxxhdpi/image_temp_location.png
  app/src/main/res/drawable/bg_blue_100_radius_8.xml
  app/src/main/res/drawable/bg_blue_300_radius_8.xml
  app/src/main/res/drawable/bg_blue_gray_200_radius_8.xml
  app/src/main/res/drawable/bg_home_gradient_above_view_pager.xml
  app/src/main/res/drawable/bg_home_tab_collapsed_item_background.xml
  app/src/main/res/drawable/bg_location_review_item.xml
  app/src/main/res/drawable/bg_white_radius_18.xml
  app/src/main/res/drawable/icon_triangle.xml
  app/src/main/res/drawable/image_home_tab_item_polygon.xml
  app/src/main/res/drawable/selector_building_review_tab_background.xml
  app/src/main/res/drawable/selector_home_tab_item_background.xml
  app/src/main/res/layout/activity_building_review.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/list_item_building_review.xml
  app/src/main/res/layout/list_item_location_review.xml
  app/src/main/res/layout/view_home_tab_layout_item.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  design/src/main/java/com/ftw/hometerview/design/Button.kt
  design/src/main/res/font/jalnan.otf
  design/src/main/res/values/colors.xml
Labels: help wanted

#23 6/collapsed layout
  app/src/main/java/com/ftw/hometerview/ui/buildingreview/BuildingReviewActivity.kt
  app/src/main/res/anim/anim_fade_in.xml
  app/src/main/res/anim/anim_fade_out.xml
  app/src/main/res/layout/activity_building_review.xml
Labels: feature ui

#22 [집터뷰 작성 - 01] 첫 번째 스텝의 주소 검색 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/di/ui/CreateReviewFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/AddressUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/extension/ActivityExtension.kt
  app/src/main/java/com/ftw/hometerview/extension/FragmentExtension.kt
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepViewModel.kt
  app/src/main/res/drawable/bg_transparent_border_gray_300_radius_8.xml
  app/src/main/res/drawable/icon_search.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/fragment_create_review_first_step.xml
  app/src/main/res/layout/list_item_create_review_search_address.xml
  app/src/main/res/values/strings.xml
  design/src/main/res/values/colors.xml
  domain/src/main/java/com/ftw/domain/usecase/address/GetAddressUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/address/GetAddressUseCaseImpl.kt
Labels: feature ui, feature logic

#24 [집터뷰 작성 - 02] 첫 번째 스텝의 거주층 선택 화면 구현
  app/src/main/java/com/ftw/hometerview/di/ui/CreateReviewFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepViewModel.kt
  app/src/main/res/drawable/icon_next.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/fragment_create_review_second_step.xml
  app/src/main/res/values/strings.xml
Labels: feature ui

#26 [집터뷰 작성 - 03] '거주층 선택 반팝업' 추가
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/residentialfloor/SelectResidentialFloorBottomSheet.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepViewModel.kt
  app/src/main/res/drawable/bg_bottom_sheet.xml
  app/src/main/res/layout/bottom_sheet_select_residential_floor.xml
  app/src/main/res/layout/fragment_create_review_second_step.xml
  app/src/main/res/layout/list_item_select_residential_floor.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  domain/src/main/java/com/ftw/domain/entity/Floor.kt
Labels: feature ui, feature logic

#28 [집터뷰 작성 - 04] 집터뷰 작성 첫 번째 단계 화면 클래스명 변경
  app/src/main/java/com/ftw/hometerview/di/ui/CreateReviewFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepInputAddressFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepInputAddressViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepSelectFloorFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepSelectFloorViewModel.kt
  app/src/main/res/layout/fragment_create_review_first_step_input_address.xml
  app/src/main/res/layout/fragment_create_review_first_step_select_floor.xml
Labels: question

#29 [집터뷰 작성 - 05] 두 번째 스텝 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/bindingadapter/RatingBarBindingAdapter.kt
  app/src/main/java/com/ftw/hometerview/di/ui/CreateReviewFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/bindingadapter/RatingBarBindingAdapter.kt
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepInputAddressFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/first/CreateReviewFirstStepSelectFloorFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepReviewFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepReviewViewModel.kt
  app/src/main/res/drawable-hdpi/icon_star_blue_40.png
  app/src/main/res/drawable-hdpi/icon_star_gray_40.png
  app/src/main/res/drawable-mdpi/icon_star_blue_40.png
  app/src/main/res/drawable-mdpi/icon_star_gray_40.png
  app/src/main/res/drawable-xhdpi/icon_star_blue_40.png
  app/src/main/res/drawable-xhdpi/icon_star_gray_40.png
  app/src/main/res/drawable-xxhdpi/icon_star_blue_40.png
  app/src/main/res/drawable-xxhdpi/icon_star_gray_40.png
  app/src/main/res/drawable-xxxhdpi/icon_star_blue_40.png
  app/src/main/res/drawable-xxxhdpi/icon_star_gray_40.png
  app/src/main/res/drawable/selector_rating_bar_icon_star_40_selected.xml
  app/src/main/res/drawable/selector_rating_bar_icon_star_40_unselected.xml
  app/src/main/res/drawable/selector_rating_bar_star_40.xml
  app/src/main/res/layout/fragment_create_review_second_step_review.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature ui

#30 [집터뷰 작성 - 06] 두 번째 단계 중 거주 기간 선택 로직 추가
  app/src/main/java/com/ftw/hometerview/ui/bottomsheet/TextListBottomSheet.kt
  app/src/main/java/com/ftw/hometerview/ui/review/CreateReviewActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepReviewFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/review/second/CreateReviewSecondStepReviewViewModel.kt
  app/src/main/res/layout/bottom_sheet_text_list.xml
  app/src/main/res/layout/list_item_bottom_sheet_text.xml
  app/src/main/res/values/strings.xml
Labels: feature ui

#32 [집터뷰 작성 - 08] 홈 화면의 변경된 디자인 적용
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewModel.kt
  app/src/main/res/drawable-xxxhdpi/image_review_inducement.png
  app/src/main/res/drawable/bg_gray_800_radius_8.xml
  app/src/main/res/drawable/selector_building_review_tab_background.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: feature ui

#37 [마이페이지 화면 - 06] 로그아웃 화면
  app/src/main/java/com/ftw/hometerview/ui/dialog/LogoutDialog.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/updatenickname/UpdateNicknameActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/drawable/round_background_white.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/activity_update_nick_name.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: feature ui

#36 [마이페이지 화면 - 05] 회원 탈퇴 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/ui/dialog/LogoutDialog.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/manageaccount/ManageAccountActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/updatenickname/UpdateNicknameActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/drawable-xhdpi/icon_check_disabled.png
  app/src/main/res/drawable-xhdpi/icon_check_enabled.png
  app/src/main/res/drawable/ic_baseline_check_circle_24.xml
  app/src/main/res/drawable/ic_baseline_uncheck_circle_24.xml
  app/src/main/res/drawable/round_background_white.xml
  app/src/main/res/drawable/selector_bg_checkbox.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/activity_update_nick_name.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  design/src/main/java/com/ftw/hometerview/design/MainButton.kt
  design/src/main/res/drawable/bg_button_disabled.xml
  design/src/main/res/drawable/selector_bg_main_button.xml
  design/src/main/res/values/attrs.xml
Labels: feature ui

#34 [마이페이지 화면 - 03] 내가 작성한 집터뷰 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/ui/MainFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/MyReviewsUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/ui/dialog/LogoutDialog.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/manageaccount/ManageAccountActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/manageaccount/ManageAccountViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/myreviews/MyReviewsActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/myreviews/MyReviewsViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/updatenickname/UpdateNicknameActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/drawable-xhdpi/icon_check_disabled.png
  app/src/main/res/drawable-xhdpi/icon_check_enabled.png
  app/src/main/res/drawable/ic_baseline_check_circle_24.xml
  app/src/main/res/drawable/ic_baseline_uncheck_circle_24.xml
  app/src/main/res/drawable/round_background_white.xml
  app/src/main/res/drawable/selector_bg_checkbox.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_my_reviews.xml
  app/src/main/res/layout/activity_update_nick_name.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/list_item_my_review.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  design/src/main/java/com/ftw/hometerview/design/MainButton.kt
  design/src/main/res/drawable/bg_button_disabled.xml
  design/src/main/res/drawable/selector_bg_main_button.xml
  design/src/main/res/values/attrs.xml
  domain/src/main/java/com/ftw/domain/entity/Review.kt
  domain/src/main/java/com/ftw/domain/usecase/buildingreview/GetBuildingReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/myreviews/GetMyReviewsUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/myreviews/GetMyReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/review/GetLocationReviewsUseCaseImpl.kt
Labels: feature ui

#33 [마이페이지 화면 - 01, 02] 마이페이지 화면, 닉네임 변경 화면 및 팝업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ftw/hometerview/di/ui/ActivityViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/ui/MainFragmentViewModelModule.kt
  app/src/main/java/com/ftw/hometerview/di/usecase/MyReviewsUseCaseModule.kt
  app/src/main/java/com/ftw/hometerview/ui/dialog/LogoutDialog.kt
  app/src/main/java/com/ftw/hometerview/ui/main/home/HomeViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageFragment.kt
  app/src/main/java/com/ftw/hometerview/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/manageaccount/ManageAccountActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/manageaccount/ManageAccountViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/myreviews/MyReviewsActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/myreviews/MyReviewsViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/updatenickname/UpdateNicknameActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/updatenickname/UpdateNicknameViewModel.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalActivity.kt
  app/src/main/java/com/ftw/hometerview/ui/withdrawal/WithdrawalViewModel.kt
  app/src/main/res/anim/appear_popup.xml
  app/src/main/res/drawable-xhdpi/icon_check_disabled.png
  app/src/main/res/drawable-xhdpi/icon_check_enabled.png
  app/src/main/res/drawable/ic_baseline_check_circle_24.xml
  app/src/main/res/drawable/ic_baseline_uncheck_circle_24.xml
  app/src/main/res/drawable/round_background_white.xml
  app/src/main/res/drawable/selector_bg_checkbox.xml
  app/src/main/res/layout/activity_create_review.xml
  app/src/main/res/layout/activity_manage_account.xml
  app/src/main/res/layout/activity_my_reviews.xml
  app/src/main/res/layout/activity_update_nick_name.xml
  app/src/main/res/layout/activity_withdrawal.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/list_item_my_review.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  design/src/main/java/com/ftw/hometerview/design/MainButton.kt
  design/src/main/res/drawable/bg_button_disabled.xml
  design/src/main/res/drawable/selector_bg_main_button.xml
  design/src/main/res/values/attrs.xml
  domain/src/main/java/com/ftw/domain/entity/Review.kt
  domain/src/main/java/com/ftw/domain/entity/User.kt
  domain/src/main/java/com/ftw/domain/usecase/buildingreview/GetBuildingReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/myreviews/GetMyReviewsUseCase.kt
  domain/src/main/java/com/ftw/domain/usecase/myreviews/GetMyReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/review/GetLocationReviewsUseCaseImpl.kt
  domain/src/main/java/com/ftw/domain/usecase/user/GetCachedUserUseCaseImpl.kt
Labels: feature ui
